config/routes.rb
Webip::Application.routes.draw do

  get    'admin/users'
  post   'admin/role/:id', to: 'admin#add_role', as: 'admin/add_role'
  delete 'admin/role/:id', to: 'admin#remove_role', as: 'admin/remove_role'

  get "home/index"

  devise_for :users

  post "vlans/set"
  get  "vlan_ips/search_all"

  resources :vlans do
    resources :vlan_ips do
      get 'release'
      get 'report'
      get 'email'
      post 'send_email'
    end
  end

root :to => 'home#index'

end

app/models/vlan_ip.rb
class VlanIp < ApplicationRecord
  resourcify
  validates_presence_of :ip, :vlan_id
  validates :hostname, length: { maximum: 50 }

  before_update :update_vlan_ip

  belongs_to :vlan, :foreign_key => "vlan_id"

  def update_vlan_ip
    if self.hostname.size > 0
      self.status = true
    end
  end

  def release
    self.hostname = ""
    self.note = ""
    self.status = false
  end

#Metodi di classe

  class << self

    def set_ips(network, vlan_id)
      ip = IPAddress network
      ip.hosts.size.times do |i|
        vlan_ip = VlanIp.new
        vlan_ip.vlan_id = vlan_id
        vlan_ip.ip = ip.hosts[i].address
        vlan_ip.status = false
        vlan_ip.hostname = ""
        vlan_ip.note = ""
        vlan_ip.save
      end
    end

    def delete_ips(vlan_ips)
      vlan_ips.size.times do |i|
        vlan_ip = VlanIp.find(vlan_ips[i].id)
        vlan_ip.destroy
      end
    end

    def search(vlan_id, sel, searched, page, per_page)
      if sel.nil? then sel = '1' end
      case sel
        when '1'
          search_note(vlan_id, searched, page, per_page)
        when '2'
          search_hostname(vlan_id, searched, page, per_page)
        when '3'
          search_ip(vlan_id, searched, page, per_page)
      end
    end

    def search_ip(vlan_id, ip, page, per_page)
      order('id asc, ip').where('vlan_id = ?  AND ip LIKE ?', "#{vlan_id}", "%#{ip}%").paginate(page: page, per_page: per_page)
    end

    def search_hostname(vlan_id, hostname, page, per_page)
      order('id asc, ip').where('vlan_id = ?  AND hostname LIKE ?', "#{vlan_id}", "%#{hostname}%").paginate(page: page, per_page: per_page)
    end

    def search_note(vlan_id, note, page, per_page)
      order('id asc, ip').where('vlan_id = ?  AND note LIKE ?', "#{vlan_id}", "%#{note}%").paginate(page: page, per_page: per_page)
    end

    def search_all(sel, searched, page, per_page)
      if sel.nil? then sel = '1' end
      case sel
        when '1'
          search_all_note(searched, page, per_page)
        when '2'
          search_all_hostname(searched, page, per_page)
        when '3'
          search_all_ip(searched, page, per_page)
      end
    end

    def search_all_ip(ip, page, per_page)
      joins(:vlan).order('id asc, ip').where('ip LIKE ?', "%#{ip}%").paginate(page: page, per_page: per_page)
    end

    def search_all_hostname(hostname, page, per_page)
      joins(:vlan).order('id asc, hostname').where('hostname LIKE ?', "%#{hostname}%").paginate(page: page, per_page: per_page)
    end

    def search_all_note(note, page, per_page)
      joins(:vlan).order('id asc, ip').where('note LIKE ?', "%#{note}%").paginate(page: page, per_page: per_page)
    end

  end

end

app/controllers/vlan_ips_controller.rb
class VlanIpsController < ApplicationController
  before_action :authenticate_user!, except: [:search_all]
  # GET /vlan_ips
  # GET /vlan_ips.json
  def index
    @edit   = helpers.set_edit(current_user)
    # legge vlan
    @vlan = Vlan.find(params[:vlan_id])
    # paginazione
    if params[:page].nil? && !session[:vlan_ips_page].nil? then
       params[:page] = session[:vlan_ips_page]
    end
    if params[:per_page].nil? && !session[:vlan_ips_per_page].nil?
      params[:per_page] = session[:vlan_ips_per_page]
    end
    # default 10 righe per pagina
    if params[:per_page].nil? || params[:per_page].to_s.strip.length == 0
      params[:per_page] = 10
    end
    # nuova ricerca riparto dalla prima pagina
    if params[:searched].to_s.strip.length > 0 && params[:searched] != session[:vlan_ips_searched]
      params[:page] = 1
    end
    # ricerca
    @vlan_ips = VlanIp.search(@vlan.id, params[:sel], params[:searched], params[:page], params[:per_page])
    # salva valori in sessione
    session[:vlan_ips_page] = params[:page]
    session[:vlan_ips_per_page] = params[:per_page]
    session[:vlan_ips_searched] = params[:searched]
    @title = t('actions.listing') + " " + t('activerecord.models.vlan_ip')
    @search_form_path = vlan_vlan_ips_path
    session[:email] = nil

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @vlan_ips }
    end
  end

  # GET /vlan_ips/1
  # GET /vlan_ips/1.json
  def show
    @vlan_ip = VlanIp.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @vlan_ip }
    end
  end

  # GET /vlan_ips/new
  # GET /vlan_ips/new.json
  def new
    @vlan_ip = VlanIp.new
    @title = t('actions.new') + " " + t('activerecord.models.vlan_ip')
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @vlan_ip }
    end
  end

  # GET /vlan_ips/1/edit
  def edit
    @vlan_ip = VlanIp.find(params[:id])
    @title = t('actions.edit') + " " + t('activerecord.models.vlan_ip')
  end

  # POST /vlan_ips
  # POST /vlan_ips.json
  def create
    @vlan_ip = VlanIp.new(params[:vlan_ip])
    @title = t('actions.new') + " " + t('activerecord.models.vlan_ip')
    respond_to do |format|
      if @vlan_ip.save
        format.html { redirect_to(vlan_vlan_ips_url) }
        format.json { render json: @vlan_ip, status: :created, location: @vlan_ip }
      else
        format.html { render action: "new" }
        format.json { render json: @vlan_ip.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /vlan_ips/1
  # PUT /vlan_ips/1.json
  def update
    @vlan_ip = VlanIp.find(params[:id])
    @title = t('actions.edit') + " " + t('activerecord.models.vlan_ip')

    respond_to do |format|
      if @vlan_ip.update(vlan_ip_params)
        format.html { redirect_to(vlan_vlan_ips_url) }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @vlan_ip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vlan_ips/1
  # DELETE /vlan_ips/1.json
  def destroy
    @vlan_ip = VlanIp.find(params[:id])
    @vlan_ip.destroy

    respond_to do |format|
      format.html { redirect_to(vlan_vlan_ips_url) }
      format.json { head :no_content }
    end
  end

  # GET /vlans/1/vlan_ips/1/release
  # GET /vlans/1/vlan_ips/1/release.json
  def release
    @vlan_ip = VlanIp.find(params[:vlan_ip_id])
    @vlan_ip.release
    @vlan_ip.update(vlan_ip_id_params)

    respond_to do |format|
      format.html { redirect_to(vlan_vlan_ips_url) }
      format.json { head :no_content }
    end
  end

  # GET /vlans/1/vlan_ips/1/report
  # GET /vlans/1/vlan_ips/1/report.json
  # GET /vlans/1/vlan_ips/1/report.pdf
  def report
    @vlan_ip = VlanIp.find(params[:vlan_ip_id])
    @vlan = Vlan.find(params[:vlan_id])
  end

  # GET /vlans/1/vlan_ips/1/email
  # GET /vlans/1/vlan_ips/1/email.json
  def email
    @title = t('actions.email') + " " + t('activerecord.models.vlan_ip')
    @vlan_ip = VlanIp.find(params[:vlan_ip_id])
    @vlan = Vlan.find(params[:vlan_id])
    if @email.nil?
      subject = 'Assegnazione IP'
      text = "Hostname: "+@vlan_ip.hostname+"\nNote: "+@vlan_ip.note+"\nIP: "+@vlan_ip.ip+
      "\nNetwork: "+@vlan.network+"\nNetmask: "+@vlan.netmask+"\nGateway: "+@vlan.gateway+"\nDNS: "+@vlan.dns
      @email = Email.new({id: 1, text: text, subject: subject, sender: "webip@lispa.it", cc: current_user.email})
    end
  end

  def send_email
    @email = Email.new(email_params)

    respond_to do |format|
      if @email.valid?
        Notifier.send_email(@email).deliver
        format.html { redirect_to(vlan_vlan_ips_url) }
        format.json { head :no_content }
      else
        format.html { render action: "email" }
        format.json { head :no_content }
      end
    end
  end

  # GET /vlan_ips/search_all
  def search_all
    @user = User.new
    # paginazione
    if params[:page].nil? && !session[:vlan_ips_all_page].nil? then
       params[:page] = session[:vlan_ips_all_page]
    end
    if params[:per_page].nil? && !session[:vlan_ips_all_per_page].nil?
      params[:per_page] = session[:vlan_ips_all_per_page]
    end
    # default 15 righe per pagina
    if params[:per_page].nil? || params[:per_page].to_s.strip.length == 0
      params[:per_page] = 15
    end
    # nuova ricerca riparto dalla prima pagina
    if params[:searched].to_s.strip.length > 0 && params[:searched] != session[:vlan_ips_all_searched]
      params[:page] = 1
    end
    # ricerca
    @vlan_ips = VlanIp.search_all(params[:sel], params[:searched], params[:page], params[:per_page])
    # salva valori in sessione
    session[:vlan_ips_all_page] = params[:page]
    session[:vlan_ips_all_per_page] = params[:per_page]
    session[:vlan_ips_all_searched] = params[:searched]

    @title = t('actions.search') + " Host"
    @search_form_path = vlan_ips_search_all_path

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @vlans }
    end
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def vlan_ip_params
      params.require(:vlan_ip).permit(:hostname, :ip, :note, :status, :vlan_id)
    end
    def vlan_ip_id_params
      params.permit(:hostname, :ip, :note, :status, :vlan_id)
    end
    def email_params
      params.require(:email).permit(:id, :text, :recipient, :subject, :sender, :cc)
    end

end

app/helpers/vlan_ips_helper.rb
module VlanIpsHelper
end

app/views/vlan_ips/_form.html.erb
<div class="container-fluid form_web col-md-offset-1 col-md-10">

<%= simple_form_for @vlan_ip, :url => vlan_vlan_ip_path do |f| %>

  <% if @vlan_ip.errors.any? %>
   <div class="alert alert-danger">
  	<a class="close" data-dismiss="alert">&#215;</a>
    <div><b> <%= t('actions.attention') %>
      <%= pluralize(@vlan_ip.errors.count, t('activerecord.errors.messages.error'), t('activerecord.errors.messages.errors')) %>:</b>
    </div>
    <ul>
    <% @vlan_ip.errors.full_messages.each do |msg| %>
      <li class="fatal_error"><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

<div class="row col-md-12">
  <%= f.input :vlan_id, as: :hidden, input_html: { size: 4 } %>
  <div class="col-md-offset-1 col-md-2 col-sm-3">
 	<%= f.input :ip, placeholder: 'xxx.xxx.xxx.xxx', input_html: { size: 15, readonly: true } %>
  </div>
  <div class="col-md-offset-2 col-md-2 col-sm-3">
 	<%= f.input :hostname, input_html: { size: 16 } %>
  </div>
  <div class="col-md-offset-2 col-md-2 col-sm-3">
    <%= f.input :status, as: :hidden %>
  </div>
</div>
<div class="col-md-offset-1 col-md-10 col-sm-12">
  <%= f.input :note, input_html: { cols: 150, rows: 8, class: 'vlan_textbox' } %>
</div>

 <div class="col-md-offset-1 col-md-10 col-sm-12">
   <%= link_to vlan_vlan_ips_path, :class => "btn btn-default btn-lg", :title => t('actions.back'), :alt => t('actions.back') do %>
     <span class="glyphicon glyphicon-arrow-left"></span> <%= t('actions.back') %>
   <% end %>
   <%= button_tag(type: 'submit', class: "btn btn-primary btn-lg") do %>
     <span class="glyphicon glyphicon-ok glyphicon-inverse"></span> <%= t('actions.update') %>
   <% end %>
 </div>

<% end %>
</div>

app/views/vlan_ips/_header.html.erb
<div class="container-fluid">
<ol class="breadcrumb col-md-2">
  <li><%= link_to Vlan, vlans_path %></li>
  <li class="active">Vlan IP</li>
</ol>
<div class="col-md-3">
  <%= render 'search_vlan_ip' %>
</div>
<div class="col-md-2">
<%= render 'per_page_vlan_ips' %>
</div>
<%= unless @vlan_ips.nil?; will_paginate @vlan_ips, :renderer => BootstrapPagination::Rails, :class => "pull-right", :inner_window => 2; end %>
</div>

app/views/vlan_ips/_header_sub.html.erb
<div class="container-fluid">
<ol class="breadcrumb col-md-6">
  <li><%= link_to Vlan, vlans_path %></li>
  <li><%= link_to "Vlan IP", vlan_vlan_ips_path %></li>
  <li class="active"><%= title %></li>
</ol>
</div>

app/views/vlan_ips/_per_page_vlan_ips.html.erb
<div class="pull-left">
<%= form_tag @search_form_path, :method => 'get', :class => "form-group pull-right form-inline", :role => "form" do %> 
  <div class="input-group">
    <%= number_field_tag :per_page, params[:per_page], :class => "pull-left form-control", :type => "number", :min => 1 %>
    <span class="input-group-btn">
      <button type="submit" class="btn btn-primary"><span class="glyphicon glyphicon-refresh"></span></button>
    </span>
  </div>
<% end %>
</div>

app/views/vlan_ips/_search_vlan_ip.html.erb
<div class="pull-left">
<%= form_tag @search_form_path, :method => 'get', :class => "form-group pull-right form-inline", :role => "form" do %> 
  <div class="input-group">
  	<span class="input-group-addon">
      <button id="selector" type="button" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Note<span class="caret"></button>
      <ul class="dropdown-menu">
        <li><a id="search_note" href="javascript:void(0)" onclick="searchFunc(this);">Note</a></li>
        <li><a id="search_host" href="javascript:void(0)" onclick="searchFunc(this);">Hostname</a></li>
        <li><a id="search_ip" href="javascript:void(0)"   onclick="searchFunc(this);">IP</a></li>
      </ul>    	
    </span>
    <%= text_field_tag :searched, params[:searched], :class => "pull-left form-control", :placeholder => 'Testo ...', :type => "search" %>
    <%= text_field_tag :sel, params[:sel], :value => "1", :type => "hidden" %>
    <span class="input-group-btn">
      <button type="submit" class="btn btn-primary"><span class="glyphicon glyphicon-search"></span></button>
    </span>
  </div>
<% end %>
</div>
<script>
  function searchFunc(obj) {
    switch(obj.id) {
      case "search_note":
  	    $('#selector').html('Note<span class="caret">'); 
  	    $('#sel').val('1');
  	    $('#searched').attr('placeholder','Testo ...');
  	    $('#searched').val("");
        break;
      case "search_host":
  	    $('#selector').html('Hostname<span class="caret">'); 
  	    $('#sel').val('2');
  	    $('#searched').attr('placeholder','Hostname ...');
  	    $('#searched').val("");
        break;
      case "search_ip":
  	    $('#selector').html('IP<span class="caret">'); 
  	    $('#sel').val('3');
  	    $('#searched').attr('placeholder','xxx.xxx.xxx.xxx');
  	    $('#searched').val("");
        break; 
      default:
        break;
    }
    return false;
  }	
</script>

app/views/vlan_ips/edit.html.erb
<%= render 'header_sub' %>
<%= render 'form' %>

app/views/vlan_ips/email.html.erb
<%= render 'header_sub' %>
<div class="container-fluid">
<%= simple_form_for @email, :url => vlan_vlan_ip_send_email_path do |f| %>

  <% if @email.errors.any? %>
    <div class="alert alert-danger">
  	  <a class="close" data-dismiss="alert">&#215;</a>
    <div><b> <%= t('actions.attention') %>
      <%= pluralize(@email.errors.count, t('activerecord.errors.messages.error'), t('activerecord.errors.messages.errors')) %>:</b>
    </div>
    <ul>
    <% @email.errors.full_messages.each do |msg| %>
      <li class="fatal_error"><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

  <div class="row col-md-12">
    <%= f.input :id, as: :hidden %>
    <div class="col-md-offset-2 col-md-2 col-sm-3">
  	  <%= f.input :sender, input_html: { size: 50, maxlength: 50, readonly: true } %>
    </div>
    <div class="col-md-offset-2 col-md-2 col-sm-3">
  	  <%= f.input :cc, input_html: { size: 50, maxlength: 50, readonly: true } %>
    </div>
  </div>
  <div class="row col-md-12">
    <div class="col-md-offset-2 col-md-4 col-sm-4">
  	  <%= f.input :recipient, placeholder: 'nome.cognome@lispa.it,nome.cognome@lispa.it...', input_html: { size: 250, maxlength: 500 } %>
    </div>
  </div>
  <div class="row col-md-12">
    <div class="col-md-offset-2 col-md-4 col-sm-5">
  	  <%= f.input :subject, input_html: { size: 50, maxlength: 100, readonly: true } %>
    </div>
  </div>
  <div class="row col-md-12">
    <div class="col-md-offset-2 col-md-8 col-sm-12">
      <%= f.input :text, as: :text, input_html: { cols: 150, rows: 10, readonly: true } %>
    </div>
  </div>

  <div class="col-md-offset-2 col-md-8 col-sm-12">
    <%= link_to vlan_vlan_ips_path, :class => "btn btn-default btn-lg", :title => t('actions.back'), :alt => t('actions.back') do %>
      <span class="glyphicon glyphicon-arrow-left"></span> <%= t('actions.back') %>
    <% end %>
    <%= button_tag(type: 'submit', class: "btn btn-primary btn-lg") do %>
      <span class="glyphicon glyphicon-ok glyphicon-inverse"></span> <%= t('actions.update') %>
    <% end %>
  </div>

 <% end %>
</div>
<br /><br />

app/views/vlan_ips/index.html.erb
<div class="col-md-12">
<%= render 'header' %>
<div class="panel-group" id="accordion" role="tablist">
<div class="panel panel-default">
  <a class="accordion-toggle" tabindex="0" data-toggle="collapse" data-parent="#accordion" href="#vlan" aria-controls="vlan">
    <div class="panel-heading panel-heading-dark" role="tab">
	  <div class="panel-title">
	  	&nbsp&nbsp Vlan: <strong><%= @vlan.vlan_code %></strong>
	    &nbsp&nbsp Network: <strong><%= @vlan.network %></strong>
  	    &nbsp&nbsp Netmask: <strong><%= @vlan.netmask %></strong>
	    &nbsp&nbsp Gateway: <strong><%= @vlan.gateway %></strong>
	    <span id="img-panel" class="glyphicon glyphicon-plus pull-right"></span>
	  </div>
    </div>
  </a>
  <div id="vlan" class="panel-collapse collapse" role="tabpanel">
	<div class="panel-body" tabindex="0">
	  <div class="table-responsive">
        <table class="table table-hover table-condensed">
          <thead>
            <tr>
              <th>Network</th>
              <th>Netmask</th>
              <th>Min</th>
              <th>Max</th>
              <th>Num</th>
              <th>Gateway</th>
              <th>DNS</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td><%= @vlan.network %></td>
              <td><%= @vlan.netmask %></td>
              <td><%= @vlan.host_min %></td>
              <td><%= @vlan.host_max %></td>
              <td><%= @vlan.hosts_num %></td>
              <td><%= @vlan.gateway %></td>
              <td><%= @vlan.dns %></td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
</div>
<div class="table-responsive">
<table class="table table-striped table-condensed table-hover">
  <thead>
  <tr>
    <th class="panel-lispa col-md-1">Ip</th>
    <th class="panel-lispa col-md-1">Hostname</th>
    <th class="panel-lispa col-md-1"><%= t('activerecord.attributes.vlan_ip.status') %></th>
    <th class="panel-lispa col-md-7">Note</th>
    <th class="panel-lispa col-md-2" colspan=4><%= t('actions.actions') %></th>
  </tr>
  </thead>
  <tbody>
  <% @vlan_ips.each_with_index do |vlan_ip, index| %>
  <tr >
    <td><%= vlan_ip.ip %></td>
    <td><%= vlan_ip.hostname %></td>
    <td><% if vlan_ip.status %><span class="glyphicon glyphicon-ok"></span><% end %></td>
    <td style="width: 50%"><%= vlan_ip.note %></td>
    <td>
      <% if @edit then @class = "btn btn-primary" else @class = "btn btn-primary disabled" end %>
      <%= link_to raw('<span class="glyphicon glyphicon-user"></span>'),
      edit_vlan_vlan_ip_path(vlan_ip.vlan_id, vlan_ip), class: @class , title: t('actions.assign'), alt: t('actions.assign'), data: {toggle: "tooltip", placement: "left" } %>
    </td>
    <td>
      <% if @edit then @class = "btn btn-default" else @class = "btn btn-default disabled" end %>
      <%= link_to raw('<span class="glyphicon glyphicon-user"></span>'),
      vlan_vlan_ip_release_path(vlan_ip.vlan_id, vlan_ip), class: @class, title: t('actions.release'), alt: t('actions.release'), data: {toggle: "tooltip", placement: "left" } %>
    </td>
    <td>
      <%= link_to raw('<span class="glyphicon glyphicon-print"></span>'),
      vlan_vlan_ip_report_path(vlan_ip.vlan_id, vlan_ip, :format=>:pdf), :class => "btn btn-default", :title => t('actions.report'), :alt => t('actions.report'), data: {toggle: "tooltip", placement: "left" } %>
    </td>
    <td>
      <%= link_to raw('<span class="glyphicon glyphicon-envelope"></span>'),
      vlan_vlan_ip_email_path(vlan_ip.vlan_id, vlan_ip), :class => "btn btn-default", :title => t('actions.email'), :alt => t('actions.email'), data: {toggle: "tooltip", placement: "left" } %>
    </td>
  </tr>
  <% end %>
  </tbody>
</table>
</div>
</div>

app/views/vlan_ips/new.html.erb
<%= render 'header_sub' %>
<%= render 'form' %>

app/views/vlan_ips/search_all.html.erb
<div class="col-md-12">
<%= render 'header' %>
<div class="table-responsive">
<table class="table table-striped table-condensed table-hover">
  <thead>
  <tr>
    <th class="panel-lispa col-md-1">Vlan</th>
    <th class="panel-lispa col-md-1">Network</th>
    <th class="panel-lispa col-md-1">Ip</th>
    <th class="panel-lispa col-md-1">Hostname</th>
    <th class="panel-lispa col-md-1"><%= t('activerecord.attributes.vlan_ip.status') %></th>
    <th class="panel-lispa col-md-7">Note</th>
  </tr>
  </thead>
  <tbody>
  <% @vlan_ips.each_with_index do |vlan_ip, index| %>
  <tr >
  	<td><%= vlan_ip.vlan.vlan_code %></td>
  	<td><%= vlan_ip.vlan.network %></td>
    <td><%= vlan_ip.ip %></td>
    <td><%= vlan_ip.hostname %></td>
    <td><% if vlan_ip.status %><span class="glyphicon glyphicon-ok"></span><% end %></td>
    <td style="width: 50%"><%= vlan_ip.note %></td>
  </tr>
  <% end %>
  </tbody>
</table>
</div>
</div>

app/views/vlan_ips/show.html.erb
<%= render 'header' %>
<div id="area_contenuti">
<p id="notice"><%= notice %></p>

<p>
  <b>Vlan:</b>
  <%= @vlan_ip.vlan_id %>
</p>

<p>
  <b>Ip:</b>
  <%= @vlan_ip.ip %>
</p>

<p>
  <b>Hostname:</b>
  <%= @vlan_ip.hostname %>
</p>

<p>
  <b>Status:</b>
  <%= @vlan_ip.status %>
</p>

<p>
  <b>Note:</b>
  <%= @vlan_ip.note %>
</p>


<%= link_to 'Edit', edit_vlan_ip_path(@vlan_ip) %> |
<%= link_to 'Back', vlan_ips_path %>
</div>