config/routes.rb
Webip::Application.routes.draw do

  get    'admin/users'
  post   'admin/role/:id', to: 'admin#add_role', as: 'admin/add_role'
  delete 'admin/role/:id', to: 'admin#remove_role', as: 'admin/remove_role'

  get "home/index"

  devise_for :users

  post "vlans/set"
  get  "vlan_ips/search_all"

  resources :vlans do
    resources :vlan_ips do
      get 'release'
      get 'report'
      get 'email'
      post 'send_email'
    end
  end

root :to => 'home#index'

end

app/views/admin/users.html.erb
<div class="col-md-12 col-sm-12">
<div class="table-responsive">
<table class="table table-striped table-condensed table-hover">
  <thead>
  <tr>
    <th class="panel-lispa col-md-1">Id</th>
    <th class="panel-lispa col-md-4">Email</th>
    <th class="panel-lispa col-md-3">Ruolo Attuale</th>
    <th class="panel-lispa col-md-3">Scelta ruolo</th>
    <th class="panel-lispa col-md-1">Aggiungi</th>
    <th class="panel-lispa col-md-1">Rimuovi</th>
  </tr>
  </thead>
  <tbody>
  <% @users.each do |user| %>
  <tr >
  	<td><%= user.id %></td>
  	<td><%= user.email %></td>
    <td>
      <% user.roles.each do |role| %>
        <%= role.name %>
      <% end %>
    </td>
    <%= form_tag admin_add_role_path(user), method: :post, class: "form-group pull-right form-inline", role: "form" do -%>
    <td>
      <%= select_tag(:role, options_for_select(@roles, 2), class: "form-control") %>
    </td>
    <td>
      <%= button_tag(type: 'submit', class: "btn btn-primary" , title: t('actions.assign'), alt: t('actions.assign'), data: {toggle: "tooltip", placement: "left" }) do %>
        <span class="glyphicon glyphicon-user"></span>
      <% end %>
    </td>
    <% end %>
    <%= form_tag admin_remove_role_path(user), method: :delete, class: "form-group pull-right form-inline", role: "form" do -%>
    <td>
      <%= button_tag(type: 'submit', class: "btn btn-default", title: t('actions.destroy'), alt: t('actions.destroy'), data: {toggle: "tooltip", placement: "left" }) do %>
        <span class="glyphicon glyphicon-trash"></span>
      <% end %>
    </td>
    <% end %>
  </tr>
  <% end %>
  </tbody>
</table>
</div>
</div>