config/routes.rb
Webip::Application.routes.draw do

  get    'admin/users'
  post   'admin/role/:id', to: 'admin#add_role', as: 'admin/add_role'
  delete 'admin/role/:id', to: 'admin#remove_role', as: 'admin/remove_role'

  get "home/index"

  devise_for :users

  post "vlans/set"
  get  "vlan_ips/search_all"

  resources :vlans do
    resources :vlan_ips do
      get 'release'
      get 'report'
      get 'email'
      post 'send_email'
    end
  end

root :to => 'home#index'

end

app/models/vlan.rb
class Vlan < ApplicationRecord
  resourcify
  attr_accessor :used, :free

  validates_presence_of :description, :host_max, :host_min, :hosts_num, :netmask, :network, :vlan_code
  validates_numericality_of :hosts_num, :vlan_code
  validates :vlan_code, :inclusion => 1..4094
  validates :vlan_code, :uniqueness => true
  validates :network, :uniqueness => true

  has_many :vlan_ips

  def set_network
    ip = IPAddress network
    self.netmask = ip.netmask
    self.host_min = ip.first.address
    self.host_max = ip.last.address
    self.hosts_num = ip.hosts.size
  end

  def hosts_count
     self.used = self.vlan_ips.where('status' => true).count
     self.free = self.hosts_num - used
     return true
  end

#Metodi di classe

  class << self
    def search(sel, searched, page, per_page)
      if sel.nil? then sel = '1' end
      case sel
        when '1'
          search_vlan_code(searched, page, per_page)
        when '2'
          search_description(searched, page, per_page)
        when '3'
          search_network(searched, page, per_page)
      end
    end

    def search_vlan_code(vlan_code, page, per_page)
      order('vlan_code asc').where('vlan_code LIKE ?', "%#{vlan_code}%").paginate(page: page, per_page: per_page)
    end

    def search_description(description, page, per_page)
      order('vlan_code asc').where('description LIKE ?', "%#{description}%").paginate(page: page, per_page: per_page)
    end

    def search_network(network, page, per_page)
      order('vlan_code asc').where('network LIKE ?', "%#{network}%").paginate(page: page, per_page: per_page)
    end
  end

end

app/controllers/vlans_controller.rb
class VlansController < ApplicationController
  before_action :authenticate_user!
  # GET /vlans
  # GET /vlans.json
  def index
    @edit   = helpers.set_edit(current_user)
    @manage = helpers.set_manage(current_user)
    # paginazione
    if params[:page].nil? && !session[:vlan_page].nil?
      params[:page] = session[:vlan_page]
    end
    if params[:per_page].nil? && !session[:vlan_per_page].nil?
      params[:per_page] = session[:vlan_per_page]
    end
    # default 10 righe per pagina
    if params[:per_page].nil? || params[:per_page].to_s.strip.length == 0
      params[:per_page] = 10
    end
    # nuova ricerca riparto dalla prima pagina
    if params[:searched].to_s.strip.length > 0 && params[:searched] != session[:vlan_searched]
      params[:page] = 1
    end
    # ricerca
    @vlans = Vlan.search(params[:sel], params[:searched], params[:page], params[:per_page])
    # salva valori in sessione
    session[:vlan_page] = params[:page]
    session[:vlan_per_page] = params[:per_page]
    session[:vlan_searched] = params[:searched]
    @title = t('actions.listing') + " " + t('activerecord.models.vlan')

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @vlans }
    end
  end

  # GET /vlans/1
  # GET /vlans/1.json
  def show
    @vlan = Vlan.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @vlan }
    end
  end

  # GET /vlans/new
  # GET /vlans/new.json
  def new
    @change = false
    @vlan = Vlan.new
    @title = t('actions.new') + " " + t('activerecord.models.vlan')
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @vlan }
    end
  end

  # GET /vlans/1/edit
  def edit
    @change = true
    @vlan = Vlan.find(params[:id])
    @title = t('actions.edit') + " " + t('activerecord.models.vlan')
  end

  # POST /vlans
  # POST /vlans.json
  def create
    @vlan = Vlan.new(vlan_params)
    @title = t('actions.new') + " " + t('activerecord.models.vlan')

    if params[:set_network] == 'set'
      set
      return
    end

    respond_to do |format|
      if @vlan.save
        VlanIp.set_ips(@vlan.network, @vlan.id)  # crea tutti gli ip della network
        format.html { redirect_to(vlans_url) }
        format.json { render json: @vlan, status: :created, location: @vlan }
      else
        format.html { render action: "new" }
        format.json { render json: @vlan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /vlans/1
  # PUT /vlans/1.json
  def update
    @vlan = Vlan.find(params[:id])
    @title = t('actions.edit') + " " + t('activerecord.models.vlan')
    respond_to do |format|
      if @vlan.update(vlan_params)
        format.html { redirect_to(vlans_url) }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @vlan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vlans/1
  # DELETE /vlans/1.json
  def destroy
    @vlan = Vlan.find(params[:id])
    @vlan.destroy
    VlanIp.delete_ips(@vlan.vlan_ips)  # cancella tutti gli ip della network

    respond_to do |format|
      format.html { redirect_to vlans_url }
      format.json { head :no_content }
    end
  end

  # POST /vlans/set
  def set
    if !@vlan.vlan_code.nil? and !@vlan.network.empty?
      @vlan.set_network
    end

    respond_to do |format|
      format.html { render action: "edit" }
      format.json { render json: @vlan }
    end
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def vlan_params
      params.require(:vlan).permit(:description, :dns, :gateway, :host_max, :host_min, :hosts_num, :netmask, :network, :vlan_code)
    end

end

app/helpers/vlans_helper.rb
module VlansHelper
end

app/views/vlans/_form.html.erb
<div class="container-fluid form_web col-md-offset-1 col-md-10">

<%= simple_form_for(@vlan) do |f| %>

<% if @vlan.errors.any? %>
  <div class="alert alert-danger">
  	<a class="close" data-dismiss="alert">&#215;</a>
    <div><b> <%= t('actions.attention') %>
      <%= pluralize(@vlan.errors.count, t('activerecord.errors.messages.error'), t('activerecord.errors.messages.errors')) %>:</b>
    </div>
    <ul>
    <% @vlan.errors.full_messages.each do |msg| %>
      <li class="fatal_error"><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<div class="row col-md-12">
<fieldset class="vlan">
  <legend>Definisci vlan (1..4094) e network:</legend>
  <div class="col-md-offset-2 col-md-3 col-sm-4">
    <%= f.input :vlan_code, as: :integer, input_html: { size: 4, maxlength: 4, min: 1, max: 4094, readonly: @change } %>
  </div>
  <div class="col-md-3 col-sm-4">
    <%= f.input :network, placeholder: 'xxx.xxx.xxx.xxx/xx', input_html: { size: 18, readonly: @change } %>
  </div>
  <div class="col-md-3 col-sm-4">
  <div class="form-group">
    <%= f.label "Calcola Rete" %><br />
    <%= button_tag(type: 'submit', class: "btn btn-primary", :name => 'set_network', :value => "set") do %>
    <span class="glyphicon glyphicon-refresh"></span>
    <% end %>
  </div>
  </div>
</fieldset>
</div>
<br />
<div class="row">
  <div class="col-md-offset-1 col-md-2 col-sm-3">
  	<%= f.input :netmask, placeholder: 'xxx.xxx.xxx.xxx', input_html: { size: 15, readonly: true } %>
  </div>
  <div class="col-md-offset-1 col-md-2 col-sm-3">
 	<%= f.input :host_min, placeholder: 'xxx.xxx.xxx.xxx', input_html: { size: 15, readonly: true } %>
  </div>
  <div class="col-md-offset-1 col-md-2 col-sm-3">
 	<%= f.input :host_max, placeholder: 'xxx.xxx.xxx.xxx', input_html: { size: 15, readonly: true } %>
  </div>
</div>
<div class="row">
  <div class="col-md-offset-1 col-md-2 col-sm-3">
    <%= f.input :hosts_num, as: :integer, input_html: { size: 10, readonly: true } %>
  </div>
  <div class="col-md-offset-1 col-md-2 col-sm-3">
 	<%= f.input :gateway, placeholder: 'xxx.xxx.xxx.xxx', input_html: { size: 15 } %>
  </div>
  <div class="col-md-offset-1 col-md-2 col-sm-3">
    <%= f.input :dns, placeholder: 'xxx.xxx.xxx.xxx', input_html: { size: 15 } %>
  </div>
</div>
<div class="row">
  <div class="col-md-offset-1 col-md-10 col-sm-12">
    <%= f.input :description, input_html: { cols: 150, rows: 8, class: 'vlan_textbox' } %>
  </div>
</div>

 <div class="col-md-offset-1 col-md-10 col-sm-12">
   <%= link_to vlans_path, :class => "btn btn-default btn-lg", :title => t('actions.back'), :alt => t('actions.back') do %>
     <span class="glyphicon glyphicon-arrow-left"></span> <%= t('actions.back') %>
   <% end %>
   <%= button_tag(type: 'submit', class: "btn btn-primary btn-lg") do %>
     <span class="glyphicon glyphicon-ok glyphicon-inverse"></span> <%= t('actions.update') %>
   <% end %>
 </div>

<% end %>
</div>
<br /><br />

app/views/vlans/_header.html.erb
<div class="col-md-12">
  <div class="col-md-3">
    <%= render 'search_vlan' %>
  </div>
  <div class="col-md-2">
    <%= render 'per_page_vlan' %>
  </div>
  <div class="col-md-offset-1">
    <%= unless @vlans.nil?; will_paginate @vlans, :renderer => BootstrapPagination::Rails; end %>
  </div>
</div>

app/views/vlans/_per_page_vlan.html.erb
<div class="pull-left">
<%= form_tag vlans_path, :method => 'get', :class => "form-group pull-right form-inline", :role => "form" do %> 
  <div class="input-group">
    <%= number_field_tag :per_page, params[:per_page], :class => "pull-left form-control", :type => "number", :min => 1 %>
    <span class="input-group-btn">
      <button type="submit" class="btn btn-primary"><span class="glyphicon glyphicon-refresh"></span></button>
    </span>
  </div>
<% end %>
</div>

app/views/vlans/_search_vlan.html.erb
<div class="pull-left">
<%= form_tag vlans_path, :method => 'get', :class => "form-group pull-right form-inline", :role => "form" do %> 
  <div class="input-group">
  	<span class="input-group-addon">
      <button id="selector" type="button" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Vlan<span class="caret"></button>
      <ul class="dropdown-menu">
        <li><a id="search_vlan" href="javascript:void(0)" onclick="searchFunc(this);">Vlan</a></li>
        <li><a id="search_description" href="javascript:void(0)" onclick="searchFunc(this);">Descrizione</a></li>
        <li><a id="search_network" href="javascript:void(0)"   onclick="searchFunc(this);">Network</a></li>
      </ul>    	
    </span>
    <%= text_field_tag :searched, params[:searched], :class => "pull-left form-control", :placeholder => 'Vlan_code ...', :type => "search" %>
    <%= text_field_tag :sel, params[:sel], :value => "1", :type => "hidden" %>
    <span class="input-group-btn">
      <button type="submit" class="btn btn-primary"><span class="glyphicon glyphicon-search"></span></button>
    </span>
  </div>
<% end %>
</div>
<script>
  function searchFunc(obj) {
    switch(obj.id) {
      case "search_vlan":
  	    $('#selector').html('Vlan<span class="caret">'); 
  	    $('#sel').val('1');
  	    $('#searched').attr('placeholder','Vlan_code ...');
  	    $('#searched').val("");
        break;
      case "search_description":
  	    $('#selector').html('Descrizione<span class="caret">'); 
  	    $('#sel').val('2');
  	    $('#searched').attr('placeholder','Testo ...');
  	    $('#searched').val("");
        break;
      case "search_network":
  	    $('#selector').html('Network<span class="caret">'); 
  	    $('#sel').val('3');
  	    $('#searched').attr('placeholder','xxx.xxx.xxx.xxx/xx');
  	    $('#searched').val("");
        break; 
      default:
        break;
    }
    return false;
  }	
</script>

app/views/vlans/edit.html.erb
<%= render 'form' %>	

app/views/vlans/index.html.erb
<div class="col-md-12">
<%= render 'header' %>
<table class="table table-striped table-condensed table-hover">
  <thead>
  <tr>
    <th class="panel-lispa">Vlan</th>
    <th class="panel-lispa">Network</th>
    <th class="panel-lispa">Netmask</th>
    <th class="panel-lispa">Host IP min</th>
    <th class="panel-lispa">Host IP max</th>
    <th class="panel-lispa">Hosts num</th>
    <th class="panel-lispa">Assegnati</th>
    <th class="panel-lispa">Liberi</th>
    <th class="panel-lispa">Gateway</th>
    <th class="panel-lispa">Dns</th>
    <th class="panel-lispa"><%= t('activerecord.attributes.vlan.description') %></th>
    <th class="panel-lispa" colspan=2><%= t('actions.actions') %></th>
  </tr>
  </thead>
  <tbody>
  <% @vlans.each_with_index do |vlan, index| %>
  <tr>
    <td><%= link_to vlan.vlan_code, vlan_vlan_ips_path(vlan) %></td>
    <td><%= vlan.network %></td>
    <td><%= vlan.netmask %></td>
    <td><%= vlan.host_min %></td>
    <td><%= vlan.host_max %></td>
    <td><%= vlan.hosts_num %></td>
    <% if vlan.hosts_count %>
    <td><span class="label label-danger"><%= vlan.used %></span></td>
    <td><span class="label label-success"><%= vlan.free %></span></td>
    <% end %>
    <td><%= vlan.gateway %></td>
    <td><%= vlan.dns %></td>
    <td><%= vlan.description %></td>
    <td>
      <% if @edit then @class = "btn btn-primary" else @class = "btn btn-primary disabled" end %>
      <%= link_to raw('<span class="glyphicon glyphicon-pencil"></span>'),
      edit_vlan_path(vlan), class: @class, title: t('actions.edit'), alt: t('actions.edit'), data: {toggle: "tooltip", placement: "left" } %>
    </td>
    <td>
      <% if @manage then @class = "btn btn-default" else @class = "btn btn-default disabled" end %>
      <%= link_to raw('<span class="glyphicon glyphicon-trash"></span>'),
      vlan, method: :delete, data: { confirm: t('actions.are_you_sure'), toggle: "tooltip", placement: "left" },
      class: @class, title: t('actions.destroy'), alt: t('actions.destroy') %>
    </td>
  </tr>
  <% end %>
  </tbody>
</table>
</div>
<% if @manage then @class = "btn btn-round red" else @class = "btn btn-round red disabled" end %>
<%= link_to new_vlan_path, class: @class, title: t('actions.new'), alt: t('actions.new') do %>
  <span class="glyphicon glyphicon-plus"></span>
<% end %>

app/views/vlans/new.html.erb
<%= render 'form' %>

app/views/vlans/show.html.erb
<div id="area_contenuti">
<p id="notice"><%= notice %></p>

<p>
  <b>Vlan:</b>
  <%= @vlan.vlan_code %>
</p>

<p>
  <b>Network:</b>
  <%= @vlan.network %>
</p>

<p>
  <b>Netmask:</b>
  <%= @vlan.netmask %>
</p>

<p>
  <b>Host min:</b>
  <%= @vlan.host_min %>
</p>

<p>
  <b>Host max:</b>
  <%= @vlan.host_max %>
</p>

<p>
  <b>Hosts num:</b>
  <%= @vlan.hosts_num %>
</p>

<p>
  <b>Gateway:</b>
  <%= @vlan.gateway %>
</p>

<p>
  <b>Dns:</b>
  <%= @vlan.dns %>
</p>

<p>
  <b>Description:</b>
  <%= @vlan.description %>
</p>


<%= link_to 'Edit', edit_vlan_path(@vlan) %> |
<%= link_to 'Back', vlans_path %>
</div>