config/routes.rb
Webip::Application.routes.draw do

  get    'admin/users'
  post   'admin/role/:id', to: 'admin#add_role', as: 'admin/add_role'
  delete 'admin/role/:id', to: 'admin#remove_role', as: 'admin/remove_role'

  get "home/index"

  devise_for :users

  post "vlans/set"
  get  "vlan_ips/search_all"

  resources :vlans do
    resources :vlan_ips do
      get 'release'
      get 'report'
      get 'email'
      post 'send_email'
    end
  end

root :to => 'home#index'

end

app/views/layouts/_area_utente.erb
<div class="area_utente">
  <div class="container-fluid">
    <span class="nome_utente">
	  <span class="glyphicon glyphicon-user white" role="presentation"></span>
      <% if user_signed_in? %>
	    Utente: <%= current_user.email %>
	    <% end %>
    </span>
    <span class="title"><%= title %></span>
    <nav class="tools_utente hidden-xs pull-right" role="menu">
      <% if user_signed_in? %>
      <% if current_user.has_role? :admin %>
      <%= link_to admin_users_path, :role => "menuitem" do %>
        <span class="glyphicon glyphicon-asterisk white" role="presentation"></span> Gestisci Utenti
      <% end %>
      <% end %>
      <% end %>
    <%= link_to vlan_ips_search_all_path, role: "menuitem", data: {turbolinks: "false"} do %>
      <span class="glyphicon glyphicon-search white" role="presentation"></span> Cerca
    <% end %>
    <%= link_to root_path, role: "menuitem", data: {turbolinks: "false"} do %>
      <span class="glyphicon glyphicon-home white" role="presentation"></span> Home
    <% end %>
    <% if user_signed_in? %>
      <%= link_to edit_user_registration_path, role: "menuitem" do %>
        <span class="glyphicon glyphicon-cog white" role="presentation"></span> Modifica profilo
      <% end %>
      <%= link_to destroy_user_session_path, method: 'delete', role: "menuitem" do %>
        <span class="glyphicon glyphicon-off white" role="presentation"></span> Logout
      <% end %>
      <% else %>
	    <%= link_to new_user_registration_path, role: "menuitem", data: {turbolinks: "false"} do %>
        <span class="glyphicon glyphicon-cog white" role="presentation"></span> Nuovo Utente
      <% end %>
      <%= link_to "#", role: "menuitem", id: 'login', data: {turbolinks: "false", toggle: "modal", target: "#login_modal", keyboard: "false" }  do %>
        <span class="glyphicon glyphicon-cog white" role="presentation"></span> Login
      <% end %>
      <%= render 'layouts/login_modal' %>
    <% end %>
    </nav>
  </div>
</div>

app/views/layouts/_area_utente.html.erb
  <div class="container-fluid area_utente">
    <span class="nome_utente">
	  <span class="glyphicon glyphicon-user white" role="presentation"></span>
      <% if user_signed_in? %>
	    Utente: <%= current_user.email %>
	    <% end %>
    </span>
    <nav class="tools_utente" role="menu">
      <% if user_signed_in? %>
      <% if current_user.has_role? :admin %>
      <%= link_to admin_users_path, :role => "menuitem" do %>
        <span class="glyphicon glyphicon-asterisk white" role="presentation"></span> Gestisci Utenti
      <% end %>
      <% end %>
      <% end %>
    <%= link_to vlan_ips_search_all_path, role: "menuitem", data: {turbolinks: "false"} do %>
      <span class="glyphicon glyphicon-search white" role="presentation"></span> Cerca
    <% end %>
    <%= link_to root_path, role: "menuitem", data: {turbolinks: "false"} do %>
      <span class="glyphicon glyphicon-home white" role="presentation"></span> Home
    <% end %>
    <% if user_signed_in? %>
      <%= link_to edit_user_registration_path, role: "menuitem" do %>
        <span class="glyphicon glyphicon-cog white" role="presentation"></span> Modifica profilo
      <% end %>
      <%= link_to destroy_user_session_path, method: 'delete', role: "menuitem" do %>
        <span class="glyphicon glyphicon-off white" role="presentation"></span> Logout
      <% end %>
      <% else %>
	    <%= link_to new_user_registration_path, role: "menuitem", data: {turbolinks: "false"} do %>
        <span class="glyphicon glyphicon-cog white" role="presentation"></span> Nuovo Utente
      <% end %>
      <%= link_to "#", role: "menuitem", id: 'login', data: {turbolinks: "false", toggle: "modal", target: "#login_modal", keyboard: "false" }  do %>
        <span class="glyphicon glyphicon-cog white" role="presentation"></span> Login
      <% end %>
      <%= render 'layouts/login_modal' %>
    <% end %>
    </nav>
  </div>

app/views/layouts/_footer.html.erb
<div id="footer" class="text-center">
  <span>&copy; Copyright Lombardia Informatica</span><span class="hidden-xs"> - tutti i diritti riservati</span>
</div>

app/views/layouts/_header.html.erb
<div id="barra_istituzionale" class="clearfix">
  <div class="logo hidden-xs">
	<a href="http://www.lispa.it">
	  <%= image_tag("new_lispa2.png", :alt => "Lombardia Informatica") %>
	</a>
  </div>
  <div>
	<div class="area_titolo">
    <span class="titolo_funzione"><%= title %></span>
	  <div class="sigla" tabindex="0"><%= t('sign') %></div>
		<span class="separatore_titolo"> | </span>
		<div class="titolo_esteso" tabindex="0"><%= t('title') %></div>
	</div>
  </div>
</div>

app/views/layouts/_login_modal.erb
<div id="login_modal" class="modal fade" tabindex="-1" data-backdrop="" aria-labelledby="LoginModal">
  <div class="modal-dialog modal-sm" role="document">
    <div class="modal-content">
      <div class='modal-header'>
        <button type="button" class="close" data-dismiss="modal" aria-label="Chiudi"><span aria-hidden="true">&times;</span></button>
        <h3 class="modal-title">Login</h3>
      </div>
      <div class='modal-body'>
        <div class="modal-body-content">
          <%= form_for(@user, :url => user_session_path) do |f| %>
          <div class="form-group">
            <%= f.label :email, :class => "control-label"%><br />
            <%= f.email_field :email, :autofocus => true, :class => "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :password, :class => "control-label" %><br />
            <%= f.password_field :password, :class => "form-control" %>
          </div>
        </div>
      </div>
      <div class='modal-footer'>
  	    <div class="form-group">
          <%= button_tag(type: 'submit', class: "btn btn-primary") do %>
            <span class="glyphicon glyphicon-ok glyphicon-inverse"></span> Collegati
          <% end %>
          <button type="button" data-dismiss="modal" class="btn btn-default">
            <span class="glyphicon glyphicon-arrow-left"></span> Chiudi
          </button>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">	
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Webip</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default navbar-fixed-top barre">
    <%= render :partial => "layouts/header" %>
    <%= render :partial => "layouts/area_utente" %>
    <%= render 'layouts/messages' %>
  </nav>
  <%= yield %>
  <nav class="navbar navbar-default navbar-fixed-bottom barre">
    <%= render :partial => "layouts/footer" %>
  </nav>
<script>
// Shorthand for $( document ).ready()
$(function () {
  /* Tooltips */
  $('[data-toggle="tooltip"]').tooltip();
  /* Accordion */
  $(".panel-collapse").on("hide.bs.collapse", function(){
    gs = this.previousElementSibling.getElementsByClassName("glyphicon-minus");
	if (gs.length>0) gs[0].className = gs[0].className.replace("minus", "plus");
  });
  $(".panel-collapse").on("show.bs.collapse", function(){
    gs = this.previousElementSibling.getElementsByClassName("glyphicon-plus");
	if (gs.length>0) gs[0].className = gs[0].className.replace("plus", "minus");
  });
});
</script>
</body>
</html>